name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3
        with:
          # A personal access token with repo scope may be required for pushing changes
          # if the default GITHUB_TOKEN permissions are too restrictive.
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/thoughtspot/tse-demo-builder-v2.git
          git fetch upstream

      - name: Merge upstream/main into your main branch
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Merge upstream changes"

      - name: Push changes to your repository
        run: git push origin main
